### ISSUE TITLE
Game crashes on launch

### ISSUE THREAD

**Issue by DEAFG0AT** [WaterMediaTeam/watermedia#10]
Here is my crash report

https://bytebin.lucko.me/7JhIxzuDob

**Comment by SrRapero720** [comment]
I am dropping support for fabric (major version 2.0.0).
That bug is NOT my fault and i can't do anything on my side. 

Fabric (for some reason) decide to break getting resources from classloader, and i want to keep my hair on my head.
Your crash is caused because critical functions (error pictures, binaries, etc) can't be extracted. Of course Forge works and Standalone Java works (fabric is the exception). docs didn't say anything about extracting and... yep... wont fix.

You can report it to Fabric (Fabric loader) to ask for a fix. but I didn't expect any response from they.

Code crashing is: https://github.com/SrRapero720/watermedia/blob/a98cf4f043d24c30005b17c849fcf0fa6f2baf5e/src/main/java/me/srrapero720/watermedia/Util.java#L45

That method always returns NULL... that means resource doesn't exists. but you can open JAR and see resource exists.

**Comment by SrRapero720** [comment]
I am rewriting assets managment/extracting

**Comment by SrRapero720** [comment]
fixed on https://github.com/SrRapero720/watermedia/commit/e6b2ecac5dc59d8f5ec8ff87124b91dd3e67a508
