### ISSUE TITLE
No m3u8 support

### ISSUE THREAD

**Issue by commet24** [WaterMediaTeam/watermedia#110]
Standart VLC supports m3u8, but your mod doesn't. Why?

**Comment by SrRapero720** [comment]
Because VLCJ Url parser sucks and the WATERMeDIA URL Parser sucks too.
This issue was fixed in v2.1.x enhancing both parsers, but it requires dependent mods release a compatibility update (for the good sake)

WaterFrames and LittleFrames will have one soon, Videoplayer maybe no (Goedix is on vacations).
