### ISSUE TITLE
Mod accessing a random URL watched on Youtube hours before the game launch

### ISSUE THREAD

**Issue by matteo335** [WaterMediaTeam/watermedia#116]
I was viewing the log of a user regarding a crash most likely not related to your mod, and noticed that a Youtube URL video was showing up seemingly because of watermedia.

The problem is it he actually watched this exact video hours before launching the game, and do not understand how the mod managed to find this video.

Maybe that could be better if they was not straight up showed in the log? And knowing/explaining as well how the mod managed to find this source or even eventually comes up to cache this?

[latest (24).log](https://github.com/user-attachments/files/18142379/latest.24.log) & https://paste.modularity.gg/paste/?content=https%3A%2F%2Fcdn.discordapp.com%2Fattachments%2F1300781978563514401%2F1317959795063525386%2Flatest_24.log&raw=false

<img width="475" alt="image" src="https://github.com/user-attachments/assets/c34c7958-b918-4358-91cb-b4dca9a7eaa9" />
<img width="208" alt="image" src="https://github.com/user-attachments/assets/e65b6d81-8c65-443f-82f1-af0dd56e6aec" />
<img width="491" alt="image" src="https://github.com/user-attachments/assets/62b14ca6-def7-4d06-b2c2-c31ca6c1f6ba" />
<img width="484" alt="image" src="https://github.com/user-attachments/assets/f50f6118-2b45-4311-a047-65bfd6e33885" />

To be fair i'm not accusing you of spying/tracking people, I am just curious and confused of how your mod seems to get this kind of information.

**Comment by SrRapero720** [comment]
its funny because watermedia doesn't have the capability to test itself at the start or track people... yet ``/jk``.

WaterMedia only attempts to load media when other mod ask for it, and assuming you're using it with waterframes, is more plausible `that someone in the server is watching kitchen nightmares in his secret base.

WaterFrames loads _any display_ placed in your world (specifically in your nearby **loaded** chunks) and unloads them if chunk gets unloaded (aka leave the server).

You can find who using this magic command: `https://github.com/SrRapero720/waterframes/wiki/Commands#waterframes-audit-option`
