### ISSUE TITLE
Vulkan Mod Compatability

### ISSUE THREAD

**Issue by Zorklis** [WaterMediaTeam/watermedia#93]
Getting crash when trying to play a video (very likely because of CreativeCore?)

Without Vulkan Mod it works fine

**Comment by Zorklis** [comment]
[hs_err_pid8228.log](https://github.com/user-attachments/files/16321236/hs_err_pid8228.log)

**Comment by SrRapero720** [comment]
Watermedia doesn't support Vulkan, that's because it do direct openGL calls instead of rely on RenderSystem (For a very good reason)

Maybe in a future add support to vulkan~~mod~~ in Watermedia? Unsure, I mean I didn't expect people using other rendering API than openGL, but I catalogued Watermedia as a library and not a mod

So, probably will stay unsupported for a while by Watermedia
